### ISSUE TITLE
You do not need the libssl package from Ubuntu

### ISSUE THREAD

**Issue by ruario** [kikonen/opera-opensuse#1]
This was a workaround for fedora only and even there it wasn't needed as a compatibility symlink would have been enough. 

For OpenSUSE you can drop all of that section.

**Comment by kikonen-fiksu** [comment]
Cool, you want to do that change? If not I look into it later today.

Anyway, I gave you full access to repo.

**Comment by kikonen** [comment]
Q: You're sure that dependency is not needed?

I.e. I tried to remove it and hit problems due to missing libudev.so.0. However, this my first time ever taking look into these rpm spec files so I surely can miss details.

EDIT: ok, that was likely due to fact that "lib" dir in build was earlier created as side-effect of that libssl copying.

**Comment by kikonen** [comment]
@ruario Can you review https://github.com/kikonen/opera-opensuse/pull/2

**Comment by kikonen** [comment]
I presume its okey now...
